language: php
sudo: false
php:
  - '5.6'
cache:
  directories:
  - sync/cache

before_script:
  - cd sync
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: sync/import.php